### ISSUE TITLE
Feishu vs Lark

### ISSUE THREAD

**Issue by IVAzraeLVI** [Ericwyn/electron-lark#25]
Hello!

This is not really an issue, it is more of a question about electron-lark (sorry, I am very new to Github, and haven't found how to post comments otherwise).

First of all, thank you for creating this app, it's incredibly helpful! My question was based on the fact that my colleagues are based in China and use Feishu, while I use electron-lark. As confirmed by Bytedance support, Lark and Feishu are two different apps that do not interact well with each other.
For instance, when I am sent a link to a Feishu Drive, I cannot download any image or even display them, as an error message pops up (not to mention that Feishu actually has more options than Lark).

So my question would be: Will you create an electron-feishu specific app or branch in the future?

Thank you in advance for reading my message!

Keep up the great work!

**Comment by Ericwyn** [comment]
Hi, thank you for your feedback, in my guess, this problem occurs because the company bytedance does not do a good job of communicating between the two products, lark and feishu.


electron-lark is a web based packager, when you open it, it will automatically display "https://feishu.com/messages", which is the home page of Feishu.

I suggest you can set the home page as the login page of lark, you can click "设置" -> "功能设置" in the menu, then in the second setting on the left, enter the login page of lark (I guess "https://www.larksuite.com/messages"), and click the blue save button

After you restart the program, you can use electron-lark just like the web version of lark

**Comment by Ericwyn** [comment]
![image](https://user-images.githubusercontent.com/16485562/126505063-7d307465-4d7b-46d0-bc06-000a440f90ff.png)
